### PR TITLE
README.md: Add Travis CI badge

### LINKED ISSUE #29: Add Travis CI badge to README.md
Add [Build Status](https://travis-ci.org/coala/rultor-python)
label: difficulty/low
Opened by @aashutoshrathi at [Gitter](https://gitter.im/coala/coala?at=59fef4c3f7299e8f537460e4)

### PR DESCRIPTION
**Pull request by psikarwal**
Update README.md

Closes #29

### CODE REVIEW

**Review by neelanshsahai — CHANGES_REQUESTED** [review]
please update your commit message
try [this link](http://coala.io/commit) and follow the commit guidelines

**Review by neelanshsahai — APPROVED** [review]
ack 95fb0f3a12d101d5f59df012cee56b8ae706c097

**Review by IpshitaC — CHANGES_REQUESTED** [review]
@psikarwal, please modify the issue reference line to say `Closes` instead of `Fixes`. As per the [guidelines](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference), we use `Fixes` if the PR fixes a bug and `Closes` for any feature/enhancement.

**Comment by psikarwal** [comment]
Thank you @IpshitaC 😉

**Comment by psikarwal** [comment]
Done @IpshitaC 👍

**Review by userzimmermann — CHANGES_REQUESTED** [review]
@neelanshsahai Don't **ack** too early ;) As @IpshitaC correctly pointed out, the commit message was not sufficient enough yet

@psikarwal You don't need to put any additional explanation into the commit message body if it doesn't add any more information. `Update README.md` is just redundant and obsolete

**Review by userzimmermann — APPROVED** [review]

**Comment by userzimmermann** [comment]
Whatever... Let's just merge this! That little redundancy in the commit message doesn't hurt ;)

Thanks @psikarwal

**Comment by userzimmermann** [comment]
ack https://github.com/coala/rultor-python/pull/34/commits/6e217ca8a06c0fb8eabe711a26fc3930d8288ab0

**Comment by userzimmermann** [comment]
@rultor merge

**Comment by psikarwal** [comment]
Thanks @userzimmermann 😉.
I'll take care in the future.

**Pull request merged**
