### PR TITLE
Dockerfile: Install python3-dev

### PR DESCRIPTION
**Pull request by supergr35**
Add the installation of python3-dev since
some packages require it and it is a good
generic addition

Closes https://github.com/coala/rultor-python/issues/6

### CODE REVIEW

**Comment by Makman2** [comment]
Okay inside docker, `apt-get` tells me that this would require additional 83MB. That's more than expected...
@jayvdb you think that is okay? Not sure if rultor caches images, if not this would definitely be an impact...

**Comment by SanketDG** [comment]
Any python library that interfaces with C would require the python-dev library, so mostly scientific libraries

If right now, we are not using any code that requires the C/Python API, then its unnecessary.

**Comment by Makman2** [comment]
okay just built the image, 2.88GB vs 2.843 (so 37MB more). Imo this is irrelevant considering that size.

**Comment by Makman2** [comment]
If someone thinks we shouldn't do this, feel free to revert. Imo this is definitely useful for others. Probably coala will use it somewhen too when doing heavy analysis stuff :+1:

**Comment by Makman2** [comment]
@rultor merge

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
