### PR TITLE
README.md: Mention upstream docker image name

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by supergr35** [comment]
LGTM

**Comment by Makman2** [comment]
@rultor merge

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Review by aashutoshrathi — APPROVED** [review]

**Comment by SanketDG** [comment]
@gitmate-bot rebase

**Comment by RaiVaibhav** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
let's just retry...
@rultor merge

**Comment by Makman2** [comment]
@rultor merge

**Comment by Makman2** [comment]
https://github.com/coala/rultor-python/pull/28 takes over.

**Pull request closed without merging**
