### PR TITLE
README.md: Added a travis CI build status badge

### PR DESCRIPTION
**Pull request by itsrainingmani**
README.md: Added the Travis CI build status badge

Closes https://github.com/coala/rultor-python/issues/29

### CODE REVIEW

**Review by userzimmermann — CHANGES_REQUESTED** [review]
@tsmanikandan Thanks for quickly contributing this PR for closing https://github.com/coala/rultor-python/issues/29 :)

Only **2** things left! Take a look at http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html and:

**[0]** Change your commit message shartlog accordingly to something like `README.md: Add ...`

**[1]** Add the issue reference `Closes https://github.com/coala/rultor-python/issues/29` to your commit message body, like I added it to https://github.com/coala/rultor-python/pull/33#issue-271616911

And before the above, do the **MOST IMPORTANT!** ;) Read http://api.coala.io/en/latest/Developers/Newcomers_Guide.html and join https://gitter.im/coala/coala and say `Hello World` there and accept the invitation to get you officially assigned to https://github.com/coala/rultor-python/issues/29

**Comment by itsrainingmani** [comment]
Hi userzimmermann. I have made the requested changes. Is there anything else I should do?

**Comment by IpshitaC** [comment]
Hey @tsmanikandan! Actually you need to modify the commit message, not the PR's description.

And I see that the issue https://github.com/coala/rultor-python/issues/29 is assigned to someone else and they too have solved it and raised a PR. If you follow the Newcomers Guide that @userzimmermann  gave, under [step 2](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-2-picking-up-an-issue) it is mentioned how to assign yourself an issue. It is essential to have an issue assigned to you so that multiple people don't end up working on the same issue at the same time.

Hope this helps! :smile:

**Comment by IpshitaC** [comment]
Hey @tsmanikandan 
Try not to close pull requests. Instead, seek feedback from the community and improve your PR until it is good to go! 😄

**Comment by userzimmermann** [comment]
@tsmanikandan And in this case: Try to think about further improvements to `README.md` and raise new issues about them :)

**Comment by itsrainingmani** [comment]
Hi @IpshitaC . Sorry, I only closed the PR since the issue had already been assigned to another person who also has an open PR. I wasn't sure what the process was. Next time I will ask :-)

**Pull request closed without merging**
