### PR TITLE
Dockerfile:Add LABEL MAINTAINER

### PR DESCRIPTION
**Pull request by RaiVaibhav**
Name of file Changed [Dockefile](https://github.com/coala/rultor-python/blob/master/Dockerfile)
Changes: replaced MAINTAINER with a LABEL maintainer 
Closes[#23](https://github.com/coala/rultor-python/issues/23)

### CODE REVIEW

**Comment by stellargo** [comment]
@RaiVaibhav correct the spelling of maintainer in your commit

**Comment by stellargo** [comment]
@RaiVaibhav before the commit title, add name of file changed. (Dockerfile: )

**Review by stellargo — COMMENTED** [review]
@RaiVaibhav 
1. in the issue yukiisbored has mentioned an '=' sign after.
2. correct the spelling of maintainer in your commit :)
3. before the commit title, add name of file changed. (Dockerfile: ). Read about it here http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html :)

**Comment by RaiVaibhav** [comment]
@stellargo  Sir maintainer spelling is correct i think and i read the  document through docker and commited it, i will add ' = ' and i will add Name of file changed

**Comment by stellargo** [comment]
@RaiVaibhav look at the commit :)
untitled
Also, please just use name not sir :)

**Comment by RaiVaibhav** [comment]
@stellargo  oh ok soory

**Comment by RaiVaibhav** [comment]
@stellargo @Makman2 can you review after changes

**Review by stellargo — APPROVED** [review]

**Comment by Makman2** [comment]
Although we don't have commit checks, the message exceeds 50 chars. Also you don't need the `=` in the commit message, just for code it's necessary ;)

**Comment by Makman2** [comment]
Oh and the referenced issue is wrong, it's pointing to this PR. Also use the full URL please if you already haven't :+1:

**Comment by RaiVaibhav** [comment]
@Makman2 the last leference points to correct change as i removed the last commited file by force push and added new file

**Comment by Makman2** [comment]
But you should reference the addressed issue, not the PR itself ;)

**Comment by RaiVaibhav** [comment]
@Makman2 I have updated the  message to 50 char but can you explain the reference part

**Comment by prnvdixit** [comment]
@RaiVaibhav  Though there are no commit checks - I think there needs to be a space after ```:```. Please, update the Shortlog to comply with same. Here is an error message from one of the comments by gitmate-bot from https://github.com/coala/coala/pull/4705.

```Shortlog of HEAD commit does not match given regex: ([^:]|[^:]+[^ ]: [A-Z0-9].*)```

**Comment by RaiVaibhav** [comment]
@Makman2 @prnvdixit  Updated :+1:, can you review it now @Makman2

**Comment by Makman2** [comment]
@rultor merge

**Comment by RaiVaibhav** [comment]
@Makman2  what i have to change now, i don't know why it did not gets merge

**Comment by RaiVaibhav** [comment]
Accidently i closed it

**Comment by Makman2** [comment]
@rultor merge

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
